services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #     COMMIT_HASH: ${COMMIT_HASH:-latest}
    image: my-test-image
    ports:
      - "5555:5555"
    volumes:
      - .:/app  # Maps the current directory to /app in the container
    command: python app.py  # Runs the application
