services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          COMMIT_HASH: ""
    image: my-test-image:${COMMIT_HASH:-latest}
    ports:
      - "5555:5555"
    volumes:
      - .:/app  # Maps the current directory to /app in the container
    command: python app.py  # Runs the application
