name: Deploy Particle Hunter Backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        ref: master

    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/test_keys
        chmod 600 ~/.ssh/test_keys
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts


    - name: Check if requirements or Dockerfile changed
      id: check_changes
      run: |
        if [ -z "${{ github.event.before }}" ]; then
          echo "First deployment - no previous commit to compare"
          echo "files_changed=true" >> $GITHUB_OUTPUT
        else
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE 'requirements.txt|Dockerfile'; then
            echo "Requirements or Dockerfile changed - rebuilding image"
            echo "files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected in requirements.txt or Dockerfile - skipping rebuild"
            echo "files_changed=false" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Deploy to Server
      env:
        DEPLOY_DIR: /home/ntkyc/information-retrieval-backend/khojai
      run: |
        log() {
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
        }
        
        ssh -i ~/.ssh/test_keys -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << EOF
          cd ${{env.DEPLOY_DIR}}
          
          # Pull latest changes
          git checkout master
          git pull origin master
          
          if [ "${{ steps.check_changes.outputs.files_changed }}" == "true" ]; then
            echo "Building new Docker image..."
            
            # Stop running containers
            docker-compose down
            
            # Remove old images before building new one
            docker images my-test-image -q | xargs -r docker rmi -f
            docker images --filter "dangling=true" -q | xargs -r docker rmi -f
            
            # Build new image
            # docker-compose build --build-arg COMMIT_HASH=$COMMIT_HASH app
            docker-compose build  app
          else
            # If no rebuild needed, just restart the containers
            echo "Stopping containers..."
            docker-compose down
          fi
          
          # Start the new containers
          echo "Starting new containers..."
          docker-compose up -d
          

        EOF
