name: Deploy Particle Hunter Backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        ref: master

    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/test_keys
        chmod 600 ~/.ssh/test_keys
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Get Commit Hash
      id: get_commit_hash
      run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Check if requirements or Dockerfile changed
      id: check_changes
      run: |
        if [ -z "${{ github.event.before }}" ]; then
          echo "files_changed=true" >> $GITHUB_OUTPUT
        else
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE 'requirements.txt|Dockerfile'; then
            echo "files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "files_changed=false" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Deploy to Server
      env:
        COMMIT_HASH: ${{ env.commit_hash }}
      run: |
        log() {
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
        }
        
        ssh -i ~/.ssh/test_keys -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << EOF
          cd /home/ntkyc/workspace/flask-app-test
          
          # Pull latest changes
          git checkout master
          git pull origin master
          
          if [ "${{ steps.check_changes.outputs.files_changed }}" == "true" ]; then
            log "Building new Docker image..."
            # Build and tag the new image
            docker-compose build --build-arg COMMIT_HASH=$COMMIT_HASH app
            # docker tag my-test-image my-test-image:$COMMIT_HASH
            
            # First, stop the running containers
            log "Stopping containers..."
            docker-compose down
            
            # Clean up old images more safely
            log "Cleaning up old images..."
            # List all images except the most recent , force remove them
            docker images my-test-image --format "{{.ID}}" | tail -n +1 | while read -r id; do
              docker rmi -f \$id || true
            done
          else
            # If no rebuild needed, just restart the containers
            log "Stopping containers..."
            docker-compose down
          fi
          
          # Start the new containers
          log "Starting new containers..."
          docker-compose up -d
          
         
