name: Deploy test in PC.

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: master

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.POLLEN_SSH_PRIVATE_KEYS }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          # eval "$(ssh-agent -s)"
          # ssh-add ~/.ssh/deploy_key

      - name: Add known hosts
        run: |
          ssh-keyscan -H "${{ secrets.SSH_PC }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          DEPLOY_DIR: /home/ilab/Manish/flask-app-test
          # SSH_AUTH_SOCK: /tmp/ssh-auth.sock
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.POLLEN_USERNAME }}@${{ secrets.SSH_PC }} << 'EOF'
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
            cd ${{env.DEPLOY_DIR}}
            pwd
            git status
            git pull origin master --rebase
            echo "Successfully entered into server and did the job"
          EOF