name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: master

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.POLLEN_SSH_PRIVATE_KEYS }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key
          
      - name: Add known hosts
        run: |
          ssh-keyscan -H "${{ secrets.POLLEN_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          DEPLOY_DIR: /home/ph/Downloads/flask-app-test
          SSH_AUTH_SOCK: /tmp/ssh-auth.sock
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.POLLEN_USERNAME }}@${{ secrets.POLLEN_HOST }} << 'EOF'
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/particle_key
            cd $DEPLOY_DIR
            git checkout master
            git pull origin master
            echo "Successfully entered into server and did the job"
          EOF